import { SaaSVendor, SaaSCategory } from "@/types";

/**
 * Enhanced SaaS vendor database with typical costs and matching patterns
 * Patterns are lowercase strings to match against transaction descriptions
 */
export const VENDORS: SaaSVendor[] = [
  // Communication & Collaboration
  {
    name: "Slack",
    category: "Communication",
    icon: "💬",
    typicalMonthlyCost: 12.5,
    patterns: ["slack", "slack technologies"],
  },
  {
    name: "Microsoft Teams",
    category: "Communication",
    icon: "💬",
    typicalMonthlyCost: 12.5,
    patterns: ["microsoft teams", "ms teams"],
  },
  {
    name: "Zoom",
    category: "Communication",
    icon: "📹",
    typicalMonthlyCost: 15.99,
    patterns: ["zoom", "zoom video", "zoom.us", "zoom communications"],
  },
  {
    name: "Google Meet",
    category: "Communication",
    icon: "📹",
    typicalMonthlyCost: 12,
    patterns: ["google meet"],
  },
  {
    name: "Webex",
    category: "Communication",
    icon: "📹",
    typicalMonthlyCost: 14.5,
    patterns: ["webex", "cisco webex"],
  },
  {
    name: "Discord",
    category: "Communication",
    icon: "💬",
    typicalMonthlyCost: 9.99,
    patterns: ["discord"],
  },
  {
    name: "Intercom",
    category: "Communication",
    icon: "💬",
    typicalMonthlyCost: 74,
    patterns: ["intercom"],
  },
  {
    name: "Twilio",
    category: "Communication",
    icon: "📱",
    typicalMonthlyCost: 50,
    patterns: ["twilio"],
  },
  {
    name: "Calendly",
    category: "Communication",
    icon: "📅",
    typicalMonthlyCost: 12,
    patterns: ["calendly"],
  },
  {
    name: "Loom",
    category: "Communication",
    icon: "🎥",
    typicalMonthlyCost: 12.5,
    patterns: ["loom"],
  },
  {
    name: "RingCentral",
    category: "Communication",
    icon: "📞",
    typicalMonthlyCost: 30,
    patterns: ["ringcentral"],
  },
  {
    name: "Dialpad",
    category: "Communication",
    icon: "📞",
    typicalMonthlyCost: 23,
    patterns: ["dialpad"],
  },
  {
    name: "Vonage",
    category: "Communication",
    icon: "📞",
    typicalMonthlyCost: 19.99,
    patterns: ["vonage"],
  },
  {
    name: "Front",
    category: "Communication",
    icon: "📧",
    typicalMonthlyCost: 59,
    patterns: ["front", "frontapp"],
  },
  {
    name: "Krisp",
    category: "Communication",
    icon: "🔇",
    typicalMonthlyCost: 12,
    patterns: ["krisp"],
  },

  // Project Management
  {
    name: "Asana",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 13.49,
    patterns: ["asana"],
  },
  {
    name: "Monday.com",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 12,
    patterns: ["monday", "monday.com"],
  },
  {
    name: "Trello",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 10,
    patterns: ["trello"],
  },
  {
    name: "Jira",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 8.15,
    patterns: ["jira", "atlassian jira"],
  },
  {
    name: "Basecamp",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 99,
    patterns: ["basecamp"],
  },
  {
    name: "Notion",
    category: "Project Management",
    icon: "📝",
    typicalMonthlyCost: 10,
    patterns: ["notion", "notion labs"],
  },
  {
    name: "ClickUp",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 10,
    patterns: ["clickup"],
  },
  {
    name: "Wrike",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 9.8,
    patterns: ["wrike"],
  },
  {
    name: "Smartsheet",
    category: "Project Management",
    icon: "📊",
    typicalMonthlyCost: 14,
    patterns: ["smartsheet"],
  },
  {
    name: "Airtable",
    category: "Project Management",
    icon: "📊",
    typicalMonthlyCost: 20,
    patterns: ["airtable"],
  },
  {
    name: "Linear",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 10,
    patterns: ["linear"],
  },
  {
    name: "Height",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 8.5,
    patterns: ["height"],
  },
  {
    name: "Teamwork",
    category: "Project Management",
    icon: "📋",
    typicalMonthlyCost: 13.99,
    patterns: ["teamwork"],
  },
  {
    name: "Todoist",
    category: "Project Management",
    icon: "✅",
    typicalMonthlyCost: 5,
    patterns: ["todoist"],
  },

  // Design
  {
    name: "Figma",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 15,
    patterns: ["figma", "figma inc"],
  },
  {
    name: "Adobe Creative Cloud",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 59.99,
    patterns: ["adobe", "adobe creative", "adobe creative cloud", "adobe inc"],
  },
  {
    name: "Sketch",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 10,
    patterns: ["sketch"],
  },
  {
    name: "Canva",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 12.99,
    patterns: ["canva"],
  },
  {
    name: "InVision",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 15,
    patterns: ["invision"],
  },
  {
    name: "Miro",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 10,
    patterns: ["miro"],
  },
  {
    name: "Framer",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 20,
    patterns: ["framer"],
  },
  {
    name: "Zeplin",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 10.75,
    patterns: ["zeplin"],
  },
  {
    name: "Abstract",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 13,
    patterns: ["abstract"],
  },
  {
    name: "Principle",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 10,
    patterns: ["principle"],
  },
  {
    name: "Lucidchart",
    category: "Design",
    icon: "📊",
    typicalMonthlyCost: 9,
    patterns: ["lucidchart", "lucid"],
  },
  {
    name: "Whimsical",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 12,
    patterns: ["whimsical"],
  },
  {
    name: "Overflow",
    category: "Design",
    icon: "🎨",
    typicalMonthlyCost: 15,
    patterns: ["overflow"],
  },

  // Dev Tools
  {
    name: "GitHub",
    category: "Dev Tools",
    icon: "💻",
    typicalMonthlyCost: 4,
    patterns: ["github"],
  },
  {
    name: "GitLab",
    category: "Dev Tools",
    icon: "💻",
    typicalMonthlyCost: 29,
    patterns: ["gitlab"],
  },
  {
    name: "Bitbucket",
    category: "Dev Tools",
    icon: "💻",
    typicalMonthlyCost: 3,
    patterns: ["bitbucket", "atlassian bitbucket"],
  },
  {
    name: "AWS",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 500,
    patterns: ["aws", "amazon web services", "amazon aws"],
  },
  {
    name: "Google Cloud",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 300,
    patterns: ["google cloud", "gcp"],
  },
  {
    name: "Microsoft Azure",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 400,
    patterns: ["azure", "microsoft azure"],
  },
  {
    name: "Heroku",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 25,
    patterns: ["heroku"],
  },
  {
    name: "Vercel",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 20,
    patterns: ["vercel"],
  },
  {
    name: "Netlify",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 19,
    patterns: ["netlify"],
  },
  {
    name: "DigitalOcean",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 50,
    patterns: ["digitalocean"],
  },
  {
    name: "Datadog",
    category: "Dev Tools",
    icon: "📊",
    typicalMonthlyCost: 15,
    patterns: ["datadog"],
  },
  {
    name: "New Relic",
    category: "Dev Tools",
    icon: "📊",
    typicalMonthlyCost: 25,
    patterns: ["new relic", "newrelic"],
  },
  {
    name: "Sentry",
    category: "Dev Tools",
    icon: "🐛",
    typicalMonthlyCost: 26,
    patterns: ["sentry"],
  },
  {
    name: "Postman",
    category: "Dev Tools",
    icon: "📮",
    typicalMonthlyCost: 14,
    patterns: ["postman"],
  },
  {
    name: "Docker",
    category: "Dev Tools",
    icon: "🐳",
    typicalMonthlyCost: 7,
    patterns: ["docker"],
  },
  {
    name: "JetBrains",
    category: "Dev Tools",
    icon: "💻",
    typicalMonthlyCost: 24.9,
    patterns: ["jetbrains"],
  },
  {
    name: "PagerDuty",
    category: "Dev Tools",
    icon: "🚨",
    typicalMonthlyCost: 21,
    patterns: ["pagerduty"],
  },
  {
    name: "OpsGenie",
    category: "Dev Tools",
    icon: "🚨",
    typicalMonthlyCost: 9,
    patterns: ["opsgenie"],
  },
  {
    name: "Snyk",
    category: "Dev Tools",
    icon: "🔒",
    typicalMonthlyCost: 52,
    patterns: ["snyk"],
  },
  {
    name: "SonarQube",
    category: "Dev Tools",
    icon: "🔍",
    typicalMonthlyCost: 150,
    patterns: ["sonarqube", "sonar"],
  },
  {
    name: "CircleCI",
    category: "Dev Tools",
    icon: "⚙️",
    typicalMonthlyCost: 30,
    patterns: ["circleci"],
  },
  {
    name: "Travis CI",
    category: "Dev Tools",
    icon: "⚙️",
    typicalMonthlyCost: 69,
    patterns: ["travis ci", "travis"],
  },
  {
    name: "Cloudflare",
    category: "Dev Tools",
    icon: "☁️",
    typicalMonthlyCost: 20,
    patterns: ["cloudflare"],
  },
  {
    name: "MongoDB",
    category: "Dev Tools",
    icon: "🗄️",
    typicalMonthlyCost: 57,
    patterns: ["mongodb"],
  },
  {
    name: "Redis",
    category: "Dev Tools",
    icon: "🗄️",
    typicalMonthlyCost: 30,
    patterns: ["redis"],
  },
  {
    name: "Elastic",
    category: "Dev Tools",
    icon: "🔍",
    typicalMonthlyCost: 95,
    patterns: ["elastic", "elasticsearch"],
  },
  {
    name: "Algolia",
    category: "Dev Tools",
    icon: "🔍",
    typicalMonthlyCost: 35,
    patterns: ["algolia"],
  },
  {
    name: "Supabase",
    category: "Dev Tools",
    icon: "🗄️",
    typicalMonthlyCost: 25,
    patterns: ["supabase"],
  },
  {
    name: "Firebase",
    category: "Dev Tools",
    icon: "🔥",
    typicalMonthlyCost: 25,
    patterns: ["firebase"],
  },
  {
    name: "PlanetScale",
    category: "Dev Tools",
    icon: "🗄️",
    typicalMonthlyCost: 29,
    patterns: ["planetscale"],
  },

  // CRM & Sales
  {
    name: "Salesforce",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 150,
    patterns: ["salesforce"],
  },
  {
    name: "HubSpot",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 90,
    patterns: ["hubspot"],
  },
  {
    name: "Pipedrive",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 14.9,
    patterns: ["pipedrive"],
  },
  {
    name: "Zoho CRM",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 20,
    patterns: ["zoho crm", "zoho"],
  },
  {
    name: "Freshsales",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 18,
    patterns: ["freshsales"],
  },
  {
    name: "Close.io",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 99,
    patterns: ["close", "close.io"],
  },
  {
    name: "Copper",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 29,
    patterns: ["copper"],
  },
  {
    name: "Apollo.io",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 49,
    patterns: ["apollo", "apollo.io"],
  },
  {
    name: "Outreach",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 100,
    patterns: ["outreach"],
  },
  {
    name: "SalesLoft",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 75,
    patterns: ["salesloft"],
  },
  {
    name: "Gong",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 100,
    patterns: ["gong"],
  },
  {
    name: "Chorus.ai",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 100,
    patterns: ["chorus"],
  },
  {
    name: "Clearbit",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 99,
    patterns: ["clearbit"],
  },
  {
    name: "ZoomInfo",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 250,
    patterns: ["zoominfo"],
  },
  {
    name: "LinkedIn Sales Navigator",
    category: "CRM",
    icon: "💼",
    typicalMonthlyCost: 99.99,
    patterns: ["linkedin sales"],
  },

  // Marketing
  {
    name: "Mailchimp",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 20,
    patterns: ["mailchimp"],
  },
  {
    name: "SendGrid",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 19.95,
    patterns: ["sendgrid"],
  },
  {
    name: "Constant Contact",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 20,
    patterns: ["constant contact"],
  },
  {
    name: "Klaviyo",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 45,
    patterns: ["klaviyo"],
  },
  {
    name: "ActiveCampaign",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 29,
    patterns: ["activecampaign"],
  },
  {
    name: "ConvertKit",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 29,
    patterns: ["convertkit"],
  },
  {
    name: "Drip",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 39,
    patterns: ["drip"],
  },
  {
    name: "Marketo",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 895,
    patterns: ["marketo"],
  },
  {
    name: "Pardot",
    category: "Marketing",
    icon: "📧",
    typicalMonthlyCost: 1250,
    patterns: ["pardot"],
  },
  {
    name: "Hootsuite",
    category: "Marketing",
    icon: "📱",
    typicalMonthlyCost: 99,
    patterns: ["hootsuite"],
  },
  {
    name: "Buffer",
    category: "Marketing",
    icon: "📱",
    typicalMonthlyCost: 15,
    patterns: ["buffer"],
  },
  {
    name: "Sprout Social",
    category: "Marketing",
    icon: "📱",
    typicalMonthlyCost: 249,
    patterns: ["sprout social"],
  },
  {
    name: "Later",
    category: "Marketing",
    icon: "📱",
    typicalMonthlyCost: 25,
    patterns: ["later"],
  },
  {
    name: "SEMrush",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 129.95,
    patterns: ["semrush"],
  },
  {
    name: "Ahrefs",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 99,
    patterns: ["ahrefs"],
  },
  {
    name: "Moz",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 99,
    patterns: ["moz"],
  },
  {
    name: "Hotjar",
    category: "Marketing",
    icon: "🔥",
    typicalMonthlyCost: 39,
    patterns: ["hotjar"],
  },
  {
    name: "Mixpanel",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 25,
    patterns: ["mixpanel"],
  },
  {
    name: "Amplitude",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 61,
    patterns: ["amplitude"],
  },
  {
    name: "Segment",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 120,
    patterns: ["segment"],
  },
  {
    name: "Google Analytics",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 150,
    patterns: ["google analytics"],
  },
  {
    name: "Heap",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 65,
    patterns: ["heap"],
  },
  {
    name: "FullStory",
    category: "Marketing",
    icon: "📊",
    typicalMonthlyCost: 199,
    patterns: ["fullstory"],
  },
  {
    name: "Unbounce",
    category: "Marketing",
    icon: "📄",
    typicalMonthlyCost: 99,
    patterns: ["unbounce"],
  },
  {
    name: "Leadpages",
    category: "Marketing",
    icon: "📄",
    typicalMonthlyCost: 49,
    patterns: ["leadpages"],
  },
  {
    name: "Typeform",
    category: "Marketing",
    icon: "📝",
    typicalMonthlyCost: 35,
    patterns: ["typeform"],
  },
  {
    name: "SurveyMonkey",
    category: "Marketing",
    icon: "📝",
    typicalMonthlyCost: 32,
    patterns: ["surveymonkey"],
  },
  {
    name: "Webflow",
    category: "Marketing",
    icon: "🌐",
    typicalMonthlyCost: 24,
    patterns: ["webflow"],
  },

  // HR & People
  {
    name: "Gusto",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 46,
    patterns: ["gusto"],
  },
  {
    name: "Rippling",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 35,
    patterns: ["rippling"],
  },
  {
    name: "BambooHR",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 99,
    patterns: ["bamboohr"],
  },
  {
    name: "Workday",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 100,
    patterns: ["workday"],
  },
  {
    name: "ADP",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 59,
    patterns: ["adp"],
  },
  {
    name: "Paychex",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 59,
    patterns: ["paychex"],
  },
  {
    name: "Namely",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 12,
    patterns: ["namely"],
  },
  {
    name: "Lever",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 100,
    patterns: ["lever"],
  },
  {
    name: "Greenhouse",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 100,
    patterns: ["greenhouse"],
  },
  {
    name: "Ashby",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 300,
    patterns: ["ashby"],
  },
  {
    name: "Deel",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 49,
    patterns: ["deel"],
  },
  {
    name: "Remote.com",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 599,
    patterns: ["remote"],
  },
  {
    name: "Oyster HR",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 499,
    patterns: ["oyster"],
  },
  {
    name: "Lattice",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 11,
    patterns: ["lattice"],
  },
  {
    name: "15Five",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 14,
    patterns: ["15five"],
  },
  {
    name: "Culture Amp",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 5,
    patterns: ["culture amp"],
  },
  {
    name: "Justworks",
    category: "HR",
    icon: "👥",
    typicalMonthlyCost: 59,
    patterns: ["justworks"],
  },

  // Finance & Accounting
  {
    name: "QuickBooks",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 30,
    patterns: ["quickbooks", "intuit quickbooks"],
  },
  {
    name: "Xero",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 40,
    patterns: ["xero"],
  },
  {
    name: "FreshBooks",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 17,
    patterns: ["freshbooks"],
  },
  {
    name: "Wave",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 0,
    patterns: ["wave accounting"],
  },
  {
    name: "Bill.com",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 69,
    patterns: ["bill.com"],
  },
  {
    name: "Brex",
    category: "Finance",
    icon: "💳",
    typicalMonthlyCost: 0,
    patterns: ["brex"],
  },
  {
    name: "Ramp",
    category: "Finance",
    icon: "💳",
    typicalMonthlyCost: 0,
    patterns: ["ramp"],
  },
  {
    name: "Divvy",
    category: "Finance",
    icon: "💳",
    typicalMonthlyCost: 0,
    patterns: ["divvy"],
  },
  {
    name: "Expensify",
    category: "Finance",
    icon: "🧾",
    typicalMonthlyCost: 5,
    patterns: ["expensify"],
  },
  {
    name: "SAP Concur",
    category: "Finance",
    icon: "🧾",
    typicalMonthlyCost: 8,
    patterns: ["concur", "sap concur"],
  },
  {
    name: "Stripe",
    category: "Finance",
    icon: "💳",
    typicalMonthlyCost: 0,
    patterns: ["stripe"],
  },
  {
    name: "Square",
    category: "Finance",
    icon: "💳",
    typicalMonthlyCost: 0,
    patterns: ["square"],
  },
  {
    name: "Plaid",
    category: "Finance",
    icon: "🔗",
    typicalMonthlyCost: 50,
    patterns: ["plaid"],
  },
  {
    name: "Bench",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 349,
    patterns: ["bench"],
  },
  {
    name: "Pilot",
    category: "Finance",
    icon: "💰",
    typicalMonthlyCost: 599,
    patterns: ["pilot"],
  },
  {
    name: "Mercury",
    category: "Finance",
    icon: "🏦",
    typicalMonthlyCost: 0,
    patterns: ["mercury"],
  },
  {
    name: "Carta",
    category: "Finance",
    icon: "📈",
    typicalMonthlyCost: 100,
    patterns: ["carta"],
  },
  {
    name: "Pulley",
    category: "Finance",
    icon: "📈",
    typicalMonthlyCost: 50,
    patterns: ["pulley"],
  },

  // Customer Support
  {
    name: "Zendesk",
    category: "Customer Support",
    icon: "🎧",
    typicalMonthlyCost: 69,
    patterns: ["zendesk"],
  },
  {
    name: "Freshdesk",
    category: "Customer Support",
    icon: "🎧",
    typicalMonthlyCost: 18,
    patterns: ["freshdesk"],
  },
  {
    name: "Help Scout",
    category: "Customer Support",
    icon: "🎧",
    typicalMonthlyCost: 25,
    patterns: ["helpscout", "help scout"],
  },
  {
    name: "Drift",
    category: "Customer Support",
    icon: "💬",
    typicalMonthlyCost: 50,
    patterns: ["drift"],
  },
  {
    name: "Crisp",
    category: "Customer Support",
    icon: "💬",
    typicalMonthlyCost: 25,
    patterns: ["crisp"],
  },
  {
    name: "Olark",
    category: "Customer Support",
    icon: "💬",
    typicalMonthlyCost: 29,
    patterns: ["olark"],
  },
  {
    name: "Tawk.to",
    category: "Customer Support",
    icon: "💬",
    typicalMonthlyCost: 0,
    patterns: ["tawk"],
  },
  {
    name: "Freshchat",
    category: "Customer Support",
    icon: "💬",
    typicalMonthlyCost: 18,
    patterns: ["freshchat"],
  },

  // Security & IT
  {
    name: "1Password",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 7.99,
    patterns: ["1password"],
  },
  {
    name: "LastPass",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 6,
    patterns: ["lastpass"],
  },
  {
    name: "Dashlane",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 8,
    patterns: ["dashlane"],
  },
  {
    name: "Bitwarden",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 5,
    patterns: ["bitwarden"],
  },
  {
    name: "Okta",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 2,
    patterns: ["okta"],
  },
  {
    name: "Auth0",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 23,
    patterns: ["auth0"],
  },
  {
    name: "Duo Security",
    category: "Security",
    icon: "🔐",
    typicalMonthlyCost: 3,
    patterns: ["duo", "duo security"],
  },
  {
    name: "CrowdStrike",
    category: "Security",
    icon: "🛡️",
    typicalMonthlyCost: 8.99,
    patterns: ["crowdstrike"],
  },
  {
    name: "Sophos",
    category: "Security",
    icon: "🛡️",
    typicalMonthlyCost: 5,
    patterns: ["sophos"],
  },
  {
    name: "Norton",
    category: "Security",
    icon: "🛡️",
    typicalMonthlyCost: 9.99,
    patterns: ["norton"],
  },
  {
    name: "McAfee",
    category: "Security",
    icon: "🛡️",
    typicalMonthlyCost: 8.33,
    patterns: ["mcafee"],
  },
  {
    name: "Jamf",
    category: "Security",
    icon: "🍎",
    typicalMonthlyCost: 8.33,
    patterns: ["jamf"],
  },
  {
    name: "Kandji",
    category: "Security",
    icon: "🍎",
    typicalMonthlyCost: 8.67,
    patterns: ["kandji"],
  },
  {
    name: "Kolide",
    category: "Security",
    icon: "🛡️",
    typicalMonthlyCost: 6,
    patterns: ["kolide"],
  },

  // Productivity & Documents
  {
    name: "Google Workspace",
    category: "Productivity",
    icon: "📄",
    typicalMonthlyCost: 12,
    patterns: ["google workspace", "g suite"],
  },
  {
    name: "Microsoft 365",
    category: "Productivity",
    icon: "📄",
    typicalMonthlyCost: 12.5,
    patterns: ["microsoft 365", "office 365", "microsoft office"],
  },
  {
    name: "Dropbox",
    category: "Productivity",
    icon: "📁",
    typicalMonthlyCost: 15,
    patterns: ["dropbox"],
  },
  {
    name: "Box",
    category: "Productivity",
    icon: "📁",
    typicalMonthlyCost: 15,
    patterns: ["box"],
  },
  {
    name: "Google Drive",
    category: "Productivity",
    icon: "📁",
    typicalMonthlyCost: 12,
    patterns: ["google drive"],
  },
  {
    name: "OneDrive",
    category: "Productivity",
    icon: "📁",
    typicalMonthlyCost: 5,
    patterns: ["onedrive"],
  },
  {
    name: "Evernote",
    category: "Productivity",
    icon: "📝",
    typicalMonthlyCost: 14.99,
    patterns: ["evernote"],
  },
  {
    name: "Obsidian",
    category: "Productivity",
    icon: "📝",
    typicalMonthlyCost: 8,
    patterns: ["obsidian"],
  },
  {
    name: "Roam Research",
    category: "Productivity",
    icon: "📝",
    typicalMonthlyCost: 15,
    patterns: ["roam"],
  },
  {
    name: "Coda",
    category: "Productivity",
    icon: "📄",
    typicalMonthlyCost: 12,
    patterns: ["coda"],
  },
  {
    name: "Confluence",
    category: "Productivity",
    icon: "📄",
    typicalMonthlyCost: 6.05,
    patterns: ["confluence", "atlassian confluence"],
  },
  {
    name: "DocuSign",
    category: "Productivity",
    icon: "✍️",
    typicalMonthlyCost: 25,
    patterns: ["docusign"],
  },
  {
    name: "PandaDoc",
    category: "Productivity",
    icon: "📄",
    typicalMonthlyCost: 29,
    patterns: ["pandadoc"],
  },
  {
    name: "HelloSign",
    category: "Productivity",
    icon: "✍️",
    typicalMonthlyCost: 20,
    patterns: ["hellosign"],
  },
  {
    name: "Grammarly",
    category: "Productivity",
    icon: "📝",
    typicalMonthlyCost: 12,
    patterns: ["grammarly"],
  },
  {
    name: "Otter.ai",
    category: "Productivity",
    icon: "🎙️",
    typicalMonthlyCost: 16.99,
    patterns: ["otter", "otter.ai"],
  },
  {
    name: "Descript",
    category: "Productivity",
    icon: "🎙️",
    typicalMonthlyCost: 15,
    patterns: ["descript"],
  },

  // AI Tools
  {
    name: "OpenAI",
    category: "AI Tools",
    icon: "🤖",
    typicalMonthlyCost: 20,
    patterns: ["openai"],
  },
  {
    name: "ChatGPT Plus",
    category: "AI Tools",
    icon: "🤖",
    typicalMonthlyCost: 20,
    patterns: ["chatgpt"],
  },
  {
    name: "Anthropic",
    category: "AI Tools",
    icon: "🤖",
    typicalMonthlyCost: 20,
    patterns: ["anthropic"],
  },
  {
    name: "Claude",
    category: "AI Tools",
    icon: "🤖",
    typicalMonthlyCost: 20,
    patterns: ["claude"],
  },
  {
    name: "Midjourney",
    category: "AI Tools",
    icon: "🎨",
    typicalMonthlyCost: 30,
    patterns: ["midjourney"],
  },
  {
    name: "Jasper AI",
    category: "AI Tools",
    icon: "✍️",
    typicalMonthlyCost: 49,
    patterns: ["jasper"],
  },
  {
    name: "Copy.ai",
    category: "AI Tools",
    icon: "✍️",
    typicalMonthlyCost: 49,
    patterns: ["copy.ai"],
  },
  {
    name: "GitHub Copilot",
    category: "AI Tools",
    icon: "💻",
    typicalMonthlyCost: 19,
    patterns: ["github copilot", "copilot"],
  },
  {
    name: "Replit",
    category: "AI Tools",
    icon: "💻",
    typicalMonthlyCost: 20,
    patterns: ["replit"],
  },
];

/**
 * Get all unique categories from the vendor database
 */
export function getCategories(): SaaSCategory[] {
  const categories = new Set<SaaSCategory>();
  VENDORS.forEach((v) => categories.add(v.category));
  return Array.from(categories);
}

/**
 * Get vendors by category
 */
export function getVendorsByCategory(
  category: SaaSCategory
): SaaSVendor[] {
  return VENDORS.filter((v) => v.category === category);
}

/**
 * Find a vendor by matching pattern against a description
 */
export function findVendorByDescription(
  description: string
): SaaSVendor | null {
  const desc = description.toLowerCase();
  for (const vendor of VENDORS) {
    for (const pattern of vendor.patterns) {
      if (desc.includes(pattern)) {
        return vendor;
      }
    }
  }
  return null;
}
