import { SaaSTool } from "@/types";

/**
 * SaaS tools database - 100+ recognized tools
 */
export const SAAS_DATABASE: Record<string, SaaSTool> = {
  // Communication & Collaboration
  slack: { name: "Slack", category: "Communication", icon: "💬" },
  "slack technologies": { name: "Slack", category: "Communication", icon: "💬" },
  "microsoft teams": { name: "Microsoft Teams", category: "Communication", icon: "💬" },
  "ms teams": { name: "Microsoft Teams", category: "Communication", icon: "💬" },
  zoom: { name: "Zoom", category: "Communication", icon: "📹" },
  "zoom video": { name: "Zoom", category: "Communication", icon: "📹" },
  "zoom.us": { name: "Zoom", category: "Communication", icon: "📹" },
  "google meet": { name: "Google Meet", category: "Communication", icon: "📹" },
  webex: { name: "Webex", category: "Communication", icon: "📹" },
  "cisco webex": { name: "Webex", category: "Communication", icon: "📹" },
  discord: { name: "Discord", category: "Communication", icon: "💬" },
  intercom: { name: "Intercom", category: "Communication", icon: "💬" },
  twilio: { name: "Twilio", category: "Communication", icon: "📱" },
  calendly: { name: "Calendly", category: "Communication", icon: "📅" },
  loom: { name: "Loom", category: "Communication", icon: "🎥" },
  ringcentral: { name: "RingCentral", category: "Communication", icon: "📞" },
  dialpad: { name: "Dialpad", category: "Communication", icon: "📞" },
  vonage: { name: "Vonage", category: "Communication", icon: "📞" },
  front: { name: "Front", category: "Communication", icon: "📧" },
  krisp: { name: "Krisp", category: "Communication", icon: "🔇" },

  // Project Management
  asana: { name: "Asana", category: "Project Management", icon: "📋" },
  monday: { name: "Monday.com", category: "Project Management", icon: "📋" },
  "monday.com": { name: "Monday.com", category: "Project Management", icon: "📋" },
  trello: { name: "Trello", category: "Project Management", icon: "📋" },
  jira: { name: "Jira", category: "Project Management", icon: "📋" },
  "atlassian jira": { name: "Jira", category: "Project Management", icon: "📋" },
  basecamp: { name: "Basecamp", category: "Project Management", icon: "📋" },
  notion: { name: "Notion", category: "Project Management", icon: "📝" },
  "notion labs": { name: "Notion", category: "Project Management", icon: "📝" },
  clickup: { name: "ClickUp", category: "Project Management", icon: "📋" },
  wrike: { name: "Wrike", category: "Project Management", icon: "📋" },
  smartsheet: { name: "Smartsheet", category: "Project Management", icon: "📊" },
  airtable: { name: "Airtable", category: "Project Management", icon: "📊" },
  linear: { name: "Linear", category: "Project Management", icon: "📋" },
  height: { name: "Height", category: "Project Management", icon: "📋" },
  teamwork: { name: "Teamwork", category: "Project Management", icon: "📋" },
  todoist: { name: "Todoist", category: "Project Management", icon: "✅" },

  // Design
  figma: { name: "Figma", category: "Design", icon: "🎨" },
  "figma inc": { name: "Figma", category: "Design", icon: "🎨" },
  adobe: { name: "Adobe Creative Cloud", category: "Design", icon: "🎨" },
  "adobe creative": { name: "Adobe Creative Cloud", category: "Design", icon: "🎨" },
  "adobe creative cloud": { name: "Adobe Creative Cloud", category: "Design", icon: "🎨" },
  "adobe inc": { name: "Adobe Creative Cloud", category: "Design", icon: "🎨" },
  sketch: { name: "Sketch", category: "Design", icon: "🎨" },
  canva: { name: "Canva", category: "Design", icon: "🎨" },
  invision: { name: "InVision", category: "Design", icon: "🎨" },
  miro: { name: "Miro", category: "Design", icon: "🎨" },
  framer: { name: "Framer", category: "Design", icon: "🎨" },
  zeplin: { name: "Zeplin", category: "Design", icon: "🎨" },
  abstract: { name: "Abstract", category: "Design", icon: "🎨" },
  principle: { name: "Principle", category: "Design", icon: "🎨" },
  lucidchart: { name: "Lucidchart", category: "Design", icon: "📊" },
  whimsical: { name: "Whimsical", category: "Design", icon: "🎨" },
  overflow: { name: "Overflow", category: "Design", icon: "🎨" },

  // Dev Tools
  github: { name: "GitHub", category: "Dev Tools", icon: "💻" },
  gitlab: { name: "GitLab", category: "Dev Tools", icon: "💻" },
  bitbucket: { name: "Bitbucket", category: "Dev Tools", icon: "💻" },
  "atlassian bitbucket": { name: "Bitbucket", category: "Dev Tools", icon: "💻" },
  aws: { name: "AWS", category: "Dev Tools", icon: "☁️" },
  "amazon web services": { name: "AWS", category: "Dev Tools", icon: "☁️" },
  "amazon aws": { name: "AWS", category: "Dev Tools", icon: "☁️" },
  "google cloud": { name: "Google Cloud", category: "Dev Tools", icon: "☁️" },
  gcp: { name: "Google Cloud", category: "Dev Tools", icon: "☁️" },
  azure: { name: "Microsoft Azure", category: "Dev Tools", icon: "☁️" },
  "microsoft azure": { name: "Microsoft Azure", category: "Dev Tools", icon: "☁️" },
  heroku: { name: "Heroku", category: "Dev Tools", icon: "☁️" },
  vercel: { name: "Vercel", category: "Dev Tools", icon: "☁️" },
  netlify: { name: "Netlify", category: "Dev Tools", icon: "☁️" },
  digitalocean: { name: "DigitalOcean", category: "Dev Tools", icon: "☁️" },
  datadog: { name: "Datadog", category: "Dev Tools", icon: "📊" },
  "new relic": { name: "New Relic", category: "Dev Tools", icon: "📊" },
  sentry: { name: "Sentry", category: "Dev Tools", icon: "🐛" },
  postman: { name: "Postman", category: "Dev Tools", icon: "📮" },
  docker: { name: "Docker", category: "Dev Tools", icon: "🐳" },
  jetbrains: { name: "JetBrains", category: "Dev Tools", icon: "💻" },
  pagerduty: { name: "PagerDuty", category: "Dev Tools", icon: "🚨" },
  opsgenie: { name: "OpsGenie", category: "Dev Tools", icon: "🚨" },
  snyk: { name: "Snyk", category: "Dev Tools", icon: "🔒" },
  sonarqube: { name: "SonarQube", category: "Dev Tools", icon: "🔍" },
  circleci: { name: "CircleCI", category: "Dev Tools", icon: "⚙️" },
  "travis ci": { name: "Travis CI", category: "Dev Tools", icon: "⚙️" },
  jenkins: { name: "Jenkins", category: "Dev Tools", icon: "⚙️" },
  terraform: { name: "Terraform", category: "Dev Tools", icon: "🏗️" },
  hashicorp: { name: "HashiCorp", category: "Dev Tools", icon: "🏗️" },
  cloudflare: { name: "Cloudflare", category: "Dev Tools", icon: "☁️" },
  mongodb: { name: "MongoDB", category: "Dev Tools", icon: "🗄️" },
  redis: { name: "Redis", category: "Dev Tools", icon: "🗄️" },
  elastic: { name: "Elastic", category: "Dev Tools", icon: "🔍" },
  elasticsearch: { name: "Elasticsearch", category: "Dev Tools", icon: "🔍" },
  algolia: { name: "Algolia", category: "Dev Tools", icon: "🔍" },
  supabase: { name: "Supabase", category: "Dev Tools", icon: "🗄️" },
  firebase: { name: "Firebase", category: "Dev Tools", icon: "🔥" },
  planetscale: { name: "PlanetScale", category: "Dev Tools", icon: "🗄️" },

  // CRM & Sales
  salesforce: { name: "Salesforce", category: "CRM", icon: "💼" },
  hubspot: { name: "HubSpot", category: "CRM", icon: "💼" },
  pipedrive: { name: "Pipedrive", category: "CRM", icon: "💼" },
  "zoho crm": { name: "Zoho CRM", category: "CRM", icon: "💼" },
  zoho: { name: "Zoho", category: "CRM", icon: "💼" },
  freshsales: { name: "Freshsales", category: "CRM", icon: "💼" },
  close: { name: "Close.io", category: "CRM", icon: "💼" },
  copper: { name: "Copper", category: "CRM", icon: "💼" },
  apollo: { name: "Apollo.io", category: "CRM", icon: "💼" },
  "apollo.io": { name: "Apollo.io", category: "CRM", icon: "💼" },
  outreach: { name: "Outreach", category: "CRM", icon: "💼" },
  salesloft: { name: "SalesLoft", category: "CRM", icon: "💼" },
  gong: { name: "Gong", category: "CRM", icon: "💼" },
  chorus: { name: "Chorus.ai", category: "CRM", icon: "💼" },
  clearbit: { name: "Clearbit", category: "CRM", icon: "💼" },
  zoominfo: { name: "ZoomInfo", category: "CRM", icon: "💼" },
  "linkedin sales": { name: "LinkedIn Sales Navigator", category: "CRM", icon: "💼" },

  // Marketing
  mailchimp: { name: "Mailchimp", category: "Marketing", icon: "📧" },
  sendgrid: { name: "SendGrid", category: "Marketing", icon: "📧" },
  "constant contact": { name: "Constant Contact", category: "Marketing", icon: "📧" },
  klaviyo: { name: "Klaviyo", category: "Marketing", icon: "📧" },
  activecampaign: { name: "ActiveCampaign", category: "Marketing", icon: "📧" },
  convertkit: { name: "ConvertKit", category: "Marketing", icon: "📧" },
  drip: { name: "Drip", category: "Marketing", icon: "📧" },
  marketo: { name: "Marketo", category: "Marketing", icon: "📧" },
  pardot: { name: "Pardot", category: "Marketing", icon: "📧" },
  hootsuite: { name: "Hootsuite", category: "Marketing", icon: "📱" },
  buffer: { name: "Buffer", category: "Marketing", icon: "📱" },
  "sprout social": { name: "Sprout Social", category: "Marketing", icon: "📱" },
  later: { name: "Later", category: "Marketing", icon: "📱" },
  semrush: { name: "SEMrush", category: "Marketing", icon: "📊" },
  ahrefs: { name: "Ahrefs", category: "Marketing", icon: "📊" },
  moz: { name: "Moz", category: "Marketing", icon: "📊" },
  hotjar: { name: "Hotjar", category: "Marketing", icon: "🔥" },
  mixpanel: { name: "Mixpanel", category: "Marketing", icon: "📊" },
  amplitude: { name: "Amplitude", category: "Marketing", icon: "📊" },
  segment: { name: "Segment", category: "Marketing", icon: "📊" },
  "google analytics": { name: "Google Analytics", category: "Marketing", icon: "📊" },
  heap: { name: "Heap", category: "Marketing", icon: "📊" },
  fullstory: { name: "FullStory", category: "Marketing", icon: "📊" },
  unbounce: { name: "Unbounce", category: "Marketing", icon: "📄" },
  leadpages: { name: "Leadpages", category: "Marketing", icon: "📄" },
  typeform: { name: "Typeform", category: "Marketing", icon: "📝" },
  surveymonkey: { name: "SurveyMonkey", category: "Marketing", icon: "📝" },
  webflow: { name: "Webflow", category: "Marketing", icon: "🌐" },

  // HR & People
  gusto: { name: "Gusto", category: "HR", icon: "👥" },
  rippling: { name: "Rippling", category: "HR", icon: "👥" },
  bamboohr: { name: "BambooHR", category: "HR", icon: "👥" },
  workday: { name: "Workday", category: "HR", icon: "👥" },
  adp: { name: "ADP", category: "HR", icon: "👥" },
  paychex: { name: "Paychex", category: "HR", icon: "👥" },
  namely: { name: "Namely", category: "HR", icon: "👥" },
  lever: { name: "Lever", category: "HR", icon: "👥" },
  greenhouse: { name: "Greenhouse", category: "HR", icon: "👥" },
  ashby: { name: "Ashby", category: "HR", icon: "👥" },
  deel: { name: "Deel", category: "HR", icon: "👥" },
  remote: { name: "Remote.com", category: "HR", icon: "👥" },
  oyster: { name: "Oyster HR", category: "HR", icon: "👥" },
  lattice: { name: "Lattice", category: "HR", icon: "👥" },
  "15five": { name: "15Five", category: "HR", icon: "👥" },
  "culture amp": { name: "Culture Amp", category: "HR", icon: "👥" },
  justworks: { name: "Justworks", category: "HR", icon: "👥" },

  // Finance & Accounting
  quickbooks: { name: "QuickBooks", category: "Finance", icon: "💰" },
  "intuit quickbooks": { name: "QuickBooks", category: "Finance", icon: "💰" },
  xero: { name: "Xero", category: "Finance", icon: "💰" },
  freshbooks: { name: "FreshBooks", category: "Finance", icon: "💰" },
  wave: { name: "Wave", category: "Finance", icon: "💰" },
  "bill.com": { name: "Bill.com", category: "Finance", icon: "💰" },
  brex: { name: "Brex", category: "Finance", icon: "💳" },
  ramp: { name: "Ramp", category: "Finance", icon: "💳" },
  divvy: { name: "Divvy", category: "Finance", icon: "💳" },
  expensify: { name: "Expensify", category: "Finance", icon: "🧾" },
  concur: { name: "SAP Concur", category: "Finance", icon: "🧾" },
  "sap concur": { name: "SAP Concur", category: "Finance", icon: "🧾" },
  stripe: { name: "Stripe", category: "Finance", icon: "💳" },
  square: { name: "Square", category: "Finance", icon: "💳" },
  plaid: { name: "Plaid", category: "Finance", icon: "🔗" },
  bench: { name: "Bench", category: "Finance", icon: "💰" },
  pilot: { name: "Pilot", category: "Finance", icon: "💰" },
  mercury: { name: "Mercury", category: "Finance", icon: "🏦" },
  carta: { name: "Carta", category: "Finance", icon: "📈" },
  pulley: { name: "Pulley", category: "Finance", icon: "📈" },

  // Customer Support
  zendesk: { name: "Zendesk", category: "Customer Support", icon: "🎧" },
  freshdesk: { name: "Freshdesk", category: "Customer Support", icon: "🎧" },
  helpscout: { name: "Help Scout", category: "Customer Support", icon: "🎧" },
  "help scout": { name: "Help Scout", category: "Customer Support", icon: "🎧" },
  drift: { name: "Drift", category: "Customer Support", icon: "💬" },
  crisp: { name: "Crisp", category: "Customer Support", icon: "💬" },
  olark: { name: "Olark", category: "Customer Support", icon: "💬" },
  tawk: { name: "Tawk.to", category: "Customer Support", icon: "💬" },
  freshchat: { name: "Freshchat", category: "Customer Support", icon: "💬" },

  // Security & IT
  "1password": { name: "1Password", category: "Security", icon: "🔐" },
  lastpass: { name: "LastPass", category: "Security", icon: "🔐" },
  dashlane: { name: "Dashlane", category: "Security", icon: "🔐" },
  bitwarden: { name: "Bitwarden", category: "Security", icon: "🔐" },
  okta: { name: "Okta", category: "Security", icon: "🔐" },
  auth0: { name: "Auth0", category: "Security", icon: "🔐" },
  duo: { name: "Duo Security", category: "Security", icon: "🔐" },
  "duo security": { name: "Duo Security", category: "Security", icon: "🔐" },
  crowdstrike: { name: "CrowdStrike", category: "Security", icon: "🛡️" },
  sophos: { name: "Sophos", category: "Security", icon: "🛡️" },
  norton: { name: "Norton", category: "Security", icon: "🛡️" },
  mcafee: { name: "McAfee", category: "Security", icon: "🛡️" },
  jamf: { name: "Jamf", category: "Security", icon: "🍎" },
  kandji: { name: "Kandji", category: "Security", icon: "🍎" },
  kolide: { name: "Kolide", category: "Security", icon: "🛡️" },

  // Productivity & Documents
  "google workspace": { name: "Google Workspace", category: "Productivity", icon: "📄" },
  "g suite": { name: "Google Workspace", category: "Productivity", icon: "📄" },
  "microsoft 365": { name: "Microsoft 365", category: "Productivity", icon: "📄" },
  "office 365": { name: "Microsoft 365", category: "Productivity", icon: "📄" },
  "microsoft office": { name: "Microsoft 365", category: "Productivity", icon: "📄" },
  dropbox: { name: "Dropbox", category: "Productivity", icon: "📁" },
  box: { name: "Box", category: "Productivity", icon: "📁" },
  "google drive": { name: "Google Drive", category: "Productivity", icon: "📁" },
  onedrive: { name: "OneDrive", category: "Productivity", icon: "📁" },
  evernote: { name: "Evernote", category: "Productivity", icon: "📝" },
  obsidian: { name: "Obsidian", category: "Productivity", icon: "📝" },
  roam: { name: "Roam Research", category: "Productivity", icon: "📝" },
  coda: { name: "Coda", category: "Productivity", icon: "📄" },
  confluence: { name: "Confluence", category: "Productivity", icon: "📄" },
  "atlassian confluence": { name: "Confluence", category: "Productivity", icon: "📄" },
  docusign: { name: "DocuSign", category: "Productivity", icon: "✍️" },
  pandadoc: { name: "PandaDoc", category: "Productivity", icon: "📄" },
  hellosign: { name: "HelloSign", category: "Productivity", icon: "✍️" },
  grammarly: { name: "Grammarly", category: "Productivity", icon: "📝" },
  otter: { name: "Otter.ai", category: "Productivity", icon: "🎙️" },
  "otter.ai": { name: "Otter.ai", category: "Productivity", icon: "🎙️" },
  descript: { name: "Descript", category: "Productivity", icon: "🎙️" },

  // AI Tools
  openai: { name: "OpenAI", category: "AI Tools", icon: "🤖" },
  chatgpt: { name: "ChatGPT Plus", category: "AI Tools", icon: "🤖" },
  anthropic: { name: "Anthropic", category: "AI Tools", icon: "🤖" },
  claude: { name: "Claude", category: "AI Tools", icon: "🤖" },
  midjourney: { name: "Midjourney", category: "AI Tools", icon: "🎨" },
  jasper: { name: "Jasper AI", category: "AI Tools", icon: "✍️" },
  "copy.ai": { name: "Copy.ai", category: "AI Tools", icon: "✍️" },
  "github copilot": { name: "GitHub Copilot", category: "AI Tools", icon: "💻" },
  replit: { name: "Replit", category: "AI Tools", icon: "💻" },
};

/**
 * Sample transaction data for demo purposes
 */
export const SAMPLE_TRANSACTIONS = [
  { description: "SLACK TECHNOLOGIES", amount: 1440, date: "2024-01-15" },
  { description: "MICROSOFT TEAMS - ANNUAL", amount: 600, date: "2024-01-10" },
  { description: "ZOOM VIDEO COMMUNICATIONS", amount: 840, date: "2024-01-12" },
  { description: "FIGMA INC", amount: 720, date: "2024-01-08" },
  { description: "ADOBE CREATIVE CLOUD", amount: 1320, date: "2024-01-05" },
  { description: "NOTION LABS INC", amount: 480, date: "2024-01-20" },
  { description: "GITHUB INC", amount: 252, date: "2024-01-18" },
  { description: "ATLASSIAN JIRA", amount: 840, date: "2024-01-22" },
  { description: "ASANA INC", amount: 660, date: "2024-01-14" },
  { description: "SALESFORCE.COM", amount: 3600, date: "2024-01-03" },
  { description: "HUBSPOT INC", amount: 2400, date: "2024-01-07" },
  { description: "DATADOG INC", amount: 1560, date: "2024-01-11" },
  { description: "AWS AMAZON WEB SERVICES", amount: 4200, date: "2024-01-01" },
  { description: "INTERCOM INC", amount: 948, date: "2024-01-16" },
  { description: "GUSTO PAYROLL", amount: 780, date: "2024-01-25" },
  { description: "QUICKBOOKS INTUIT", amount: 420, date: "2024-01-28" },
  { description: "1PASSWORD", amount: 192, date: "2024-01-19" },
  { description: "MAILCHIMP", amount: 600, date: "2024-01-21" },
  { description: "ZENDESK INC", amount: 1140, date: "2024-01-13" },
  { description: "FRESHDESK", amount: 720, date: "2024-01-17" },
  { description: "CANVA PTY LTD", amount: 156, date: "2024-01-24" },
  { description: "TRELLO - ATLASSIAN", amount: 120, date: "2024-01-26" },
  { description: "GRAMMARLY INC", amount: 144, date: "2024-01-27" },
  { description: "CALENDLY", amount: 192, date: "2024-01-09" },
  { description: "LOOM INC", amount: 150, date: "2024-01-23" },
];

/**
 * Application configuration
 */
export const APP_CONFIG = {
  name: "SubSleuth",
  description: "Stop Bleeding Money on Forgotten Software",
  url: "https://subsleuth.com",
  email: "hello@subsleuth.com",
};
